CREATE TYPE IF NOT EXISTS ACCOUNT_TYPE AS ENUM ('STANDARD', 'PREMIUM', 'GOLD');
CREATE TYPE IF NOT EXISTS TRANSACTION_TYPE AS ENUM ('IN', 'OUT');

CREATE TABLE IF NOT EXISTS account (
    id UUID PRIMARY KEY DEFAULT uuidv4(),
    account_type ACCOUNT_TYPE NOT NULL
);

CREATE TABLE IF NOT EXISTS transaction (
    id UUID PRIMARY KEY DEFAULT uuidv4(),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    transaction_type TRANSACTION_TYPE NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    account_id UUID NOT NULL,
    reason VARCHAR(100),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE
);